import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import ts from "typescript";

import { publicModules } from "../public-api.config";
import type { PublicModule } from "../public-api.config";

interface CollectedExports {
  types: string[];
  values: string[];
}

interface PackageExportTarget {
  types: string;
  import: string;
}

type PackageExports = Record<string, PackageExportTarget | string>;

const scriptDir = import.meta.dirname;
const packageRoot = path.resolve(scriptDir, "..");
const srcDir = path.join(packageRoot, "src");
const indexPath = path.join(srcDir, "index.ts");
const packageJsonPath = path.join(packageRoot, "package.json");
const checkMode = process.argv.includes("--check");
const generatedHeader =
  "// Generated by scripts/generate-public-api.ts. Do not edit directly.\n\n";

function readText(filePath: string): string {
  return readFileSync(filePath, "utf-8");
}

function writeText(filePath: string, content: string): void {
  writeFileSync(filePath, content);
}

function resolveSourcePath(modulePath: PublicModule["source"]): string {
  for (const extension of [".ts", ".tsx"] as const) {
    const sourcePath = path.join(srcDir, `${modulePath.slice(2)}${extension}`);

    try {
      readText(sourcePath);
      return sourcePath;
    } catch {
      // Try the next supported source extension.
    }
  }

  throw new Error(`Could not find source module for ${modulePath}`);
}

function hasExportModifier(statement: ts.Statement): boolean {
  return Boolean(
    ts.canHaveModifiers(statement) &&
    ts
      .getModifiers(statement)
      ?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword)
  );
}

function addUnique(list: string[], name: string): void {
  if (!list.includes(name)) {
    list.push(name);
  }
}

function collectExports(moduleConfig: PublicModule): CollectedExports {
  const sourcePath = resolveSourcePath(moduleConfig.source);
  const sourceText = readText(sourcePath);
  const sourceFile = ts.createSourceFile(
    sourcePath,
    sourceText,
    ts.ScriptTarget.Latest,
    true,
    sourcePath.endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS
  );
  const excludedExports = new Set(moduleConfig.excludeExports);
  const collected: CollectedExports = { types: [], values: [] };

  for (const statement of sourceFile.statements) {
    if (hasExportModifier(statement)) {
      if (ts.isFunctionDeclaration(statement) && statement.name) {
        addUnique(collected.values, statement.name.text);
      }

      if (ts.isClassDeclaration(statement) && statement.name) {
        addUnique(collected.values, statement.name.text);
      }

      if (ts.isEnumDeclaration(statement)) {
        addUnique(collected.values, statement.name.text);
      }

      if (ts.isVariableStatement(statement)) {
        for (const declaration of statement.declarationList.declarations) {
          addUnique(collected.values, declaration.name.getText(sourceFile));
        }
      }

      if (
        ts.isInterfaceDeclaration(statement) ||
        ts.isTypeAliasDeclaration(statement)
      ) {
        addUnique(collected.types, statement.name.text);
      }
    }

    if (
      ts.isExportDeclaration(statement) &&
      statement.exportClause &&
      ts.isNamedExports(statement.exportClause)
    ) {
      for (const element of statement.exportClause.elements) {
        const name = element.name.text;

        if (statement.isTypeOnly || element.isTypeOnly) {
          addUnique(collected.types, name);
        } else {
          addUnique(collected.values, name);
        }
      }
    }
  }

  return {
    types: collected.types.filter((name) => !excludedExports.has(name)),
    values: collected.values.filter((name) => !excludedExports.has(name)),
  };
}

function formatExportLine(
  keyword: "export" | "export type",
  names: string[],
  modulePath: string
): string {
  const compactLine = `${keyword} { ${names.join(", ")} } from "${modulePath}";`;

  if (compactLine.length <= 80) {
    return compactLine;
  }

  return `${keyword} {\n  ${names.join(",\n  ")},\n} from "${modulePath}";`;
}

function assertNoDuplicateExports(
  exportKind: "type" | "value",
  names: string[],
  seenNames: Map<string, string>,
  modulePath: string
): void {
  for (const name of names) {
    const previousModule = seenNames.get(name);

    if (previousModule) {
      throw new Error(
        `Duplicate ${exportKind} export "${name}" from ${modulePath}; already exported from ${previousModule}. Add an explicit excludeExports entry if this is intentional.`
      );
    }

    seenNames.set(name, modulePath);
  }
}

function buildIndexSource(): string {
  const lines: string[] = [generatedHeader.trimEnd()];
  const seenValues = new Map<string, string>();
  const seenTypes = new Map<string, string>();

  for (const moduleConfig of publicModules) {
    const collected = collectExports(moduleConfig);

    assertNoDuplicateExports(
      "value",
      collected.values,
      seenValues,
      moduleConfig.source
    );
    assertNoDuplicateExports(
      "type",
      collected.types,
      seenTypes,
      moduleConfig.source
    );

    if (collected.values.length > 0) {
      lines.push(
        formatExportLine("export", collected.values, moduleConfig.source)
      );
    }

    if (collected.types.length > 0) {
      lines.push(
        formatExportLine("export type", collected.types, moduleConfig.source)
      );
    }
  }

  return `${lines.join("\n")}\n`;
}

function packageTargetForSource(
  source: PublicModule["source"]
): PackageExportTarget {
  const distPath = source.replace("./", "./dist/");

  return {
    import: `${distPath}.js`,
    types: `${distPath}.d.ts`,
  };
}

function buildPackageExports(): PackageExports {
  const exportsMap: PackageExports = {
    ".": {
      import: "./dist/index.js",
      types: "./dist/index.d.ts",
    },
  };

  for (const moduleConfig of publicModules) {
    exportsMap[moduleConfig.subpath] = packageTargetForSource(
      moduleConfig.source
    );
  }

  return {
    ...exportsMap,
    "./base-ui/*": {
      import: "./dist/base-ui/*.js",
      types: "./dist/base-ui/*.d.ts",
    },
    "./components/*": {
      import: "./dist/components/*.js",
      types: "./dist/components/*.d.ts",
    },
    "./globals.css": "./src/styles/globals.css",
    "./hooks/*": {
      import: "./dist/hooks/*.js",
      types: "./dist/hooks/*.d.ts",
    },
    "./lib/*": {
      import: "./dist/lib/*.js",
      types: "./dist/lib/*.d.ts",
    },
    "./styles/globals.css": "./src/styles/globals.css",
  };
}

function buildPackageJsonSource(): string {
  const packageJson = JSON.parse(readText(packageJsonPath)) as Record<
    string,
    unknown
  >;
  packageJson.exports = buildPackageExports();

  return `${JSON.stringify(packageJson, null, 2)}\n`;
}

function checkGeneratedFile(
  filePath: string,
  expectedContent: string
): boolean {
  const actualContent = readText(filePath);

  if (actualContent === expectedContent) {
    return true;
  }

  process.stderr.write(
    `${filePath} is out of date. Run bun run generate:api.\n`
  );
  return false;
}

function run(): void {
  const indexSource = buildIndexSource();
  const packageJsonSource = buildPackageJsonSource();

  if (checkMode) {
    const indexIsCurrent = checkGeneratedFile(indexPath, indexSource);
    const packageJsonIsCurrent = checkGeneratedFile(
      packageJsonPath,
      packageJsonSource
    );

    if (!(indexIsCurrent && packageJsonIsCurrent)) {
      process.exitCode = 1;
    }

    return;
  }

  writeText(indexPath, indexSource);
  writeText(packageJsonPath, packageJsonSource);
}

run();
