export interface PublicModule {
  source: `./${string}`;
  subpath: `./${string}`;
  excludeExports?: readonly string[];
}

export const publicModules = [
  { source: "./base-ui/csp-provider", subpath: "./csp-provider" },
  { source: "./base-ui/direction-provider", subpath: "./direction-provider" },
  { source: "./base-ui/merge-props", subpath: "./merge-props" },
  { source: "./base-ui/use-render", subpath: "./use-render" },
  { source: "./components/accordion", subpath: "./accordion" },
  { source: "./components/alert", subpath: "./alert" },
  { source: "./components/alert-dialog", subpath: "./alert-dialog" },
  { source: "./components/autocomplete", subpath: "./autocomplete" },
  { source: "./components/avatar", subpath: "./avatar" },
  { source: "./components/badge", subpath: "./badge" },
  { source: "./components/breadcrumb", subpath: "./breadcrumb" },
  { source: "./components/button", subpath: "./button" },
  { source: "./components/calendar", subpath: "./calendar" },
  { source: "./components/card", subpath: "./card" },
  { source: "./components/checkbox", subpath: "./checkbox" },
  { source: "./components/checkbox-group", subpath: "./checkbox-group" },
  { source: "./components/collapsible", subpath: "./collapsible" },
  { source: "./components/combobox", subpath: "./combobox" },
  { source: "./components/command", subpath: "./command" },
  { source: "./components/context-menu", subpath: "./context-menu" },
  { source: "./components/dialog", subpath: "./dialog" },
  { source: "./components/drawer", subpath: "./drawer" },
  { source: "./components/empty", subpath: "./empty" },
  { source: "./components/field", subpath: "./field" },
  { source: "./components/fieldset", subpath: "./fieldset" },
  { source: "./components/form", subpath: "./form" },
  { source: "./components/frame", subpath: "./frame" },
  { source: "./components/group", subpath: "./group" },
  { source: "./components/input", subpath: "./input" },
  { source: "./components/input-group", subpath: "./input-group" },
  { source: "./components/kbd", subpath: "./kbd" },
  { source: "./components/label", subpath: "./label" },
  { source: "./components/menu", subpath: "./menu" },
  { source: "./components/meter", subpath: "./meter" },
  { source: "./components/number-field", subpath: "./number-field" },
  { source: "./components/otp-field", subpath: "./otp-field" },
  { source: "./components/pagination", subpath: "./pagination" },
  { source: "./components/popover", subpath: "./popover" },
  { source: "./components/preview-card", subpath: "./preview-card" },
  { source: "./components/progress", subpath: "./progress" },
  { source: "./components/radio-group", subpath: "./radio-group" },
  { source: "./components/scroll-area", subpath: "./scroll-area" },
  { source: "./components/select", subpath: "./select" },
  { source: "./components/separator", subpath: "./separator" },
  { source: "./components/sheet", subpath: "./sheet" },
  { source: "./components/skeleton", subpath: "./skeleton" },
  { source: "./components/slider", subpath: "./slider" },
  { source: "./components/spinner", subpath: "./spinner" },
  { source: "./components/switch", subpath: "./switch" },
  { source: "./components/table", subpath: "./table" },
  { source: "./components/tabs", subpath: "./tabs" },
  {
    excludeExports: ["FieldPrimitive"],
    source: "./components/textarea",
    subpath: "./textarea",
  },
  { source: "./components/toast", subpath: "./toast" },
  { source: "./components/toggle", subpath: "./toggle" },
  { source: "./components/toggle-group", subpath: "./toggle-group" },
  { source: "./components/toolbar", subpath: "./toolbar" },
  { source: "./components/tooltip", subpath: "./tooltip" },
  {
    source: "./hooks/use-copy-to-clipboard",
    subpath: "./use-copy-to-clipboard",
  },
  { source: "./hooks/use-media-query", subpath: "./use-media-query" },
  { source: "./lib/utils", subpath: "./utils" },
] as const satisfies readonly PublicModule[];
